"""Add pgvector and embeddings

Revision ID: e537dc4a9e93
Revises: bed1659d7368
Create Date: 2026-07-01 14:19:06.579017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e537dc4a9e93'
down_revision: Union[str, Sequence[str], None] = 'bed1659d7368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('chunks', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('chunks', sa.Column('embedding_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('repositories', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'error_message')
    op.drop_column('chunks', 'embedding_created_at')
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
