"""Add title and created_at to ChatSession

Revision ID: ea5e8800362d
Revises: e537dc4a9e93
Create Date: 2026-07-01 23:38:23.203042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5e8800362d'
down_revision: Union[str, Sequence[str], None] = 'e537dc4a9e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('title', sa.String(), nullable=False))
    op.add_column('chat_sessions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'created_at')
    op.drop_column('chat_sessions', 'title')
    # ### end Alembic commands ###
